#!/bin/bash

BBV_DIR=${BBV_DIR:-../bbv}

if [ ! -d $BBV_DIR ]; then
  echo 'Check out a copy of https://github.com/mit-plv/bbv in the parent directory and build it.'
  exit 1
fi

set -ex
cd sail
make
cd ..
coqc -R $BBV_DIR/theories bbv -R sail Sail riscv_extras.v
coqc -R $BBV_DIR/theories bbv -R sail Sail riscv_types.v
coqc -R $BBV_DIR/theories bbv -R sail Sail riscv.v
